### ISSUE TITLE
过于落后，可以展示

### ISSUE THREAD

**Issue by cmd1152** [Googologyer/notems#1]
你这个我很难评价你，我看见“安装”的时候还以为是 nodejs lib，结果啥也不是，不如我的nodejs lib好用
![image](https://github.com/Googologyer/notems/assets/109453324/113293fb-4a97-4880-a6c0-3d01ee8f02b1)
![image](https://github.com/Googologyer/notems/assets/109453324/61854e76-7740-4ddb-961a-037c04b13850)

**Comment by Googologyer** [comment]
你这个就是用了Node.js，其实覆盖功能差不多。

**Comment by cmd1152** [comment]
> 你这个就是用了Node.js，其实覆盖功能差不多。

神经，这可没有 cors限制

**Comment by Googologyer** [comment]
是多了个命令行的功能，但是与网页版没有什么区别。

**Comment by cmd1152** [comment]
> 你这个就是用了Node.js，其实覆盖功能差不多。

神经，这可没有 cors限制

**Comment by cmd1152** [comment]
> 是多了个命令行的功能，但是与网页版没有什么区别。

没有cors

**Comment by cmd1152** [comment]
占用更低
速度快

**Comment by Googologyer** [comment]
你的这个Node.js有GitHub吗？

另外，您对我们的项目有什么建议吗？

**Comment by Googologyer** [comment]
Closed because no-reply
