### ISSUE TITLE
这不是就是fetch包吗，怎么算核心技术

### ISSUE THREAD

**Issue by cmd1152** [Googologyer/notems#2]
你这个顶多算抓包然后封装了函数，和au等说的技术不是同一个东西，你这个局限性很大，比如只能在浏览器运行，不能跨站垮页面，但是au等说的技术是占用小、速度快的、没有同源限制的技术，当然，我也不会过多描述他，还有 note.ms/0 写的是事实，你直接删了什么意思，你好歹指出哪里不对吧，不得不说你也是臭名远扬了，隔壁一堆网站的管理员都来讨伐了，都把证据贴脸上了，你还在notebbs上造谣，我一质疑你就说没证据，那好，你怎么证明 note.ms /0 是假的， note.ms/0有关你的事情已经写得很清楚了

**Comment by Googologyer** [comment]
故意辱骂他人，锁。另外辱骂的违规行为正在向github举报。

**Comment by Googologyer** [comment]
我能编辑你的issue
